let dummy = {
  location: {
    name: "Seoul",
    region: "",
    country: "South Korea",
    lat: 37.57,
    lon: 127.0,
    tz_id: "Asia/Seoul",
    localtime_epoch: 1606025326,
    localtime: "2020-11-22 15:08"
  },
  current: {
    last_updated_epoch: 1605997408,
    last_updated: "2020-11-22 07:23",
    temp_c: 8.9,
    temp_f: 48.0,
    is_day: 1,
    condition: {
      text: "Partly cloudy",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003
    },
    wind_mph: 9.2,
    wind_kph: 14.8,
    wind_degree: 295,
    wind_dir: "WNW",
    pressure_mb: 1022.0,
    pressure_in: 30.7,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 52,
    cloud: 43,
    feelslike_c: 6.6,
    feelslike_f: 43.9,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 3.0,
    gust_mph: 10.5,
    gust_kph: 16.9
  },
  forecast: {
    forecastday: [
      {
        date: "2020-11-22",
        date_epoch: 1606003200,
        day: {
          maxtemp_c: 9.6,
          maxtemp_f: 49.3,
          mintemp_c: 3.4,
          mintemp_f: 38.1,
          avgtemp_c: 7.6,
          avgtemp_f: 45.7,
          maxwind_mph: 13.2,
          maxwind_kph: 21.2,
          totalprecip_mm: 3.6,
          totalprecip_in: 0.14,
          avgvis_km: 8.8,
          avgvis_miles: 5.0,
          avghumidity: 60.0,
          daily_will_it_rain: 1,
          daily_chance_of_rain: "75",
          daily_will_it_snow: 0,
          daily_chance_of_snow: "0",
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063
          },
          uv: 2.0
        },
        astro: {
          sunrise: "07:19 AM",
          sunset: "05:17 PM",
          moonrise: "01:34 PM",
          moonset: "No moonset",
          moon_phase: "First Quarter",
          moon_illumination: "48"
        },
        hour: [
          {
            time_epoch: 1605970800,
            time: "2020-11-22 00:00",
            temp_c: 10.0,
            temp_f: 50.0,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1023.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 100,
            feelslike_c: 9.5,
            feelslike_f: 49.1,
            windchill_c: 9.5,
            windchill_f: 49.1,
            heatindex_c: 10.0,
            heatindex_f: 50.0,
            dewpoint_c: 3.1,
            dewpoint_f: 37.6,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 4.5,
            gust_kph: 7.2
          },
          {
            time_epoch: 1605974400,
            time: "2020-11-22 01:00",
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.1,
            precip_in: 0.0,
            humidity: 64,
            cloud: 95,
            feelslike_c: 9.3,
            feelslike_f: 48.7,
            windchill_c: 9.3,
            windchill_f: 48.7,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 0,
            chance_of_rain: "22",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 7.3,
            vis_miles: 4.0,
            gust_mph: 4.5,
            gust_kph: 7.2
          },
          {
            time_epoch: 1605978000,
            time: "2020-11-22 02:00",
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 260,
            wind_dir: "W",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 66,
            cloud: 90,
            feelslike_c: 9.2,
            feelslike_f: 48.6,
            windchill_c: 9.2,
            windchill_f: 48.6,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 0,
            chance_of_rain: "44",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 4.7,
            vis_miles: 2.0,
            gust_mph: 4.5,
            gust_kph: 7.2
          },
          {
            time_epoch: 1605981600,
            time: "2020-11-22 03:00",
            temp_c: 9.5,
            temp_f: 49.1,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 280,
            wind_dir: "W",
            pressure_mb: 1021.0,
            pressure_in: 30.6,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 68,
            cloud: 85,
            feelslike_c: 9.0,
            feelslike_f: 48.2,
            windchill_c: 9.0,
            windchill_f: 48.2,
            heatindex_c: 9.5,
            heatindex_f: 49.1,
            dewpoint_c: 3.9,
            dewpoint_f: 39.0,
            will_it_rain: 0,
            chance_of_rain: "66",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 2.0,
            vis_miles: 1.0,
            gust_mph: 4.5,
            gust_kph: 7.2
          },
          {
            time_epoch: 1605985200,
            time: "2020-11-22 04:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 285,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.6,
            precip_mm: 0.7,
            precip_in: 0.03,
            humidity: 72,
            cloud: 90,
            feelslike_c: 7.5,
            feelslike_f: 45.5,
            windchill_c: 7.5,
            windchill_f: 45.5,
            heatindex_c: 8.5,
            heatindex_f: 47.3,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: "68",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 4.3,
            vis_miles: 2.0,
            gust_mph: 5.8,
            gust_kph: 9.4
          },
          {
            time_epoch: 1605988800,
            time: "2020-11-22 05:00",
            temp_c: 7.6,
            temp_f: 45.7,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 290,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.1,
            precip_in: 0.04,
            humidity: 75,
            cloud: 95,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 7.6,
            heatindex_f: 45.7,
            dewpoint_c: 3.4,
            dewpoint_f: 38.1,
            will_it_rain: 1,
            chance_of_rain: "71",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 6.7,
            vis_miles: 4.0,
            gust_mph: 6.9,
            gust_kph: 11.2
          },
          {
            time_epoch: 1605992400,
            time: "2020-11-22 06:00",
            temp_c: 6.6,
            temp_f: 43.9,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 296,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.4,
            precip_in: 0.06,
            humidity: 79,
            cloud: 100,
            feelslike_c: 4.4,
            feelslike_f: 39.9,
            windchill_c: 4.4,
            windchill_f: 39.9,
            heatindex_c: 6.6,
            heatindex_f: 43.9,
            dewpoint_c: 3.2,
            dewpoint_f: 37.8,
            will_it_rain: 1,
            chance_of_rain: "73",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 8.3,
            gust_kph: 13.3
          },
          {
            time_epoch: 1605996000,
            time: "2020-11-22 07:00",
            temp_c: 6.9,
            temp_f: 44.4,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 300,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.5,
            precip_in: 0.06,
            humidity: 75,
            cloud: 94,
            feelslike_c: 5.1,
            feelslike_f: 41.2,
            windchill_c: 5.1,
            windchill_f: 41.2,
            heatindex_c: 6.9,
            heatindex_f: 44.4,
            dewpoint_c: 2.8,
            dewpoint_f: 37.0,
            will_it_rain: 1,
            chance_of_rain: "74",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 6.9,
            gust_kph: 11.2
          },
          {
            time_epoch: 1605999600,
            time: "2020-11-22 08:00",
            temp_c: 7.2,
            temp_f: 45.0,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 304,
            wind_dir: "NW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.7,
            precip_in: 0.07,
            humidity: 71,
            cloud: 87,
            feelslike_c: 5.9,
            feelslike_f: 42.6,
            windchill_c: 5.9,
            windchill_f: 42.6,
            heatindex_c: 7.2,
            heatindex_f: 45.0,
            dewpoint_c: 2.4,
            dewpoint_f: 36.3,
            will_it_rain: 1,
            chance_of_rain: "74",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 5.8,
            gust_kph: 9.4
          },
          {
            time_epoch: 1606003200,
            time: "2020-11-22 09:00",
            temp_c: 7.5,
            temp_f: 45.5,
            is_day: 1,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
              code: 1180
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 308,
            wind_dir: "NW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.8,
            precip_in: 0.07,
            humidity: 68,
            cloud: 81,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 7.5,
            heatindex_f: 45.5,
            dewpoint_c: 2.0,
            dewpoint_f: 35.6,
            will_it_rain: 1,
            chance_of_rain: "75",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 4.5,
            gust_kph: 7.2
          },
          {
            time_epoch: 1606006800,
            time: "2020-11-22 10:00",
            temp_c: 8.0,
            temp_f: 46.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 304,
            wind_dir: "NW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 1.2,
            precip_in: 0.05,
            humidity: 63,
            cloud: 69,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 8.0,
            heatindex_f: 46.4,
            dewpoint_c: 1.2,
            dewpoint_f: 34.2,
            will_it_rain: 0,
            chance_of_rain: "50",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 6.5,
            gust_kph: 10.4
          },
          {
            time_epoch: 1606010400,
            time: "2020-11-22 11:00",
            temp_c: 8.4,
            temp_f: 47.1,
            is_day: 1,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/293.png",
              code: 1180
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 299,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.6,
            precip_in: 0.02,
            humidity: 57,
            cloud: 56,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 8.4,
            heatindex_f: 47.1,
            dewpoint_c: 0.4,
            dewpoint_f: 32.7,
            will_it_rain: 0,
            chance_of_rain: "25",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 8.5,
            gust_kph: 13.7
          },
          {
            time_epoch: 1606014000,
            time: "2020-11-22 12:00",
            temp_c: 8.9,
            temp_f: 48.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 295,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 43,
            feelslike_c: 6.6,
            feelslike_f: 43.9,
            windchill_c: 6.6,
            windchill_f: 43.9,
            heatindex_c: 8.9,
            heatindex_f: 48.0,
            dewpoint_c: -0.4,
            dewpoint_f: 31.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9
          },
          {
            time_epoch: 1606017600,
            time: "2020-11-22 13:00",
            temp_c: 9.1,
            temp_f: 48.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 294,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 35,
            feelslike_c: 6.8,
            feelslike_f: 44.2,
            windchill_c: 6.8,
            windchill_f: 44.2,
            heatindex_c: 9.1,
            heatindex_f: 48.4,
            dewpoint_c: -1.0,
            dewpoint_f: 30.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.3
          },
          {
            time_epoch: 1606021200,
            time: "2020-11-22 14:00",
            temp_c: 9.4,
            temp_f: 48.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 293,
            wind_dir: "WNW",
            pressure_mb: 1021.0,
            pressure_in: 30.6,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 46,
            cloud: 26,
            feelslike_c: 7.1,
            feelslike_f: 44.8,
            windchill_c: 7.1,
            windchill_f: 44.8,
            heatindex_c: 9.4,
            heatindex_f: 48.9,
            dewpoint_c: -1.6,
            dewpoint_f: 29.1,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.2,
            gust_kph: 18.0
          },
          {
            time_epoch: 1606024800,
            time: "2020-11-22 15:00",
            temp_c: 9.6,
            temp_f: 49.3,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 292,
            wind_dir: "WNW",
            pressure_mb: 1021.0,
            pressure_in: 30.6,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 17,
            feelslike_c: 7.3,
            feelslike_f: 45.1,
            windchill_c: 7.3,
            windchill_f: 45.1,
            heatindex_c: 9.6,
            heatindex_f: 49.3,
            dewpoint_c: -2.2,
            dewpoint_f: 28.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4
          },
          {
            time_epoch: 1606028400,
            time: "2020-11-22 16:00",
            temp_c: 8.1,
            temp_f: 46.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 299,
            wind_dir: "WNW",
            pressure_mb: 1022.0,
            pressure_in: 30.6,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 13,
            feelslike_c: 5.3,
            feelslike_f: 41.5,
            windchill_c: 5.3,
            windchill_f: 41.5,
            heatindex_c: 8.1,
            heatindex_f: 46.6,
            dewpoint_c: -2.3,
            dewpoint_f: 27.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.0,
            gust_kph: 20.9
          },
          {
            time_epoch: 1606032000,
            time: "2020-11-22 17:00",
            temp_c: 6.7,
            temp_f: 44.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003
            },
            wind_mph: 12.1,
            wind_kph: 19.4,
            wind_degree: 305,
            wind_dir: "NW",
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 10,
            feelslike_c: 3.2,
            feelslike_f: 37.8,
            windchill_c: 3.2,
            windchill_f: 37.8,
            heatindex_c: 6.7,
            heatindex_f: 44.1,
            dewpoint_c: -2.5,
            dewpoint_f: 27.5,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.8,
            gust_kph: 23.8
          },
          {
            time_epoch: 1606035600,
            time: "2020-11-22 18:00",
            temp_c: 5.2,
            temp_f: 41.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1023.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 6,
            feelslike_c: 1.2,
            feelslike_f: 34.2,
            windchill_c: 1.2,
            windchill_f: 34.2,
            heatindex_c: 5.2,
            heatindex_f: 41.4,
            dewpoint_c: -2.6,
            dewpoint_f: 27.3,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.3,
            gust_kph: 26.3
          },
          {
            time_epoch: 1606039200,
            time: "2020-11-22 19:00",
            temp_c: 4.6,
            temp_f: 40.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1023.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 7,
            feelslike_c: 0.6,
            feelslike_f: 33.1,
            windchill_c: 0.6,
            windchill_f: 33.1,
            heatindex_c: 4.6,
            heatindex_f: 40.3,
            dewpoint_c: -3.8,
            dewpoint_f: 25.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.0,
            gust_kph: 24.1
          },
          {
            time_epoch: 1606042800,
            time: "2020-11-22 20:00",
            temp_c: 4.0,
            temp_f: 39.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1024.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 8,
            feelslike_c: 0.1,
            feelslike_f: 32.2,
            windchill_c: 0.1,
            windchill_f: 32.2,
            heatindex_c: 4.0,
            heatindex_f: 39.2,
            dewpoint_c: -5.0,
            dewpoint_f: 23.0,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.4,
            gust_kph: 21.6
          },
          {
            time_epoch: 1606046400,
            time: "2020-11-22 21:00",
            temp_c: 3.4,
            temp_f: 38.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 311,
            wind_dir: "NW",
            pressure_mb: 1024.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 49,
            cloud: 9,
            feelslike_c: -0.5,
            feelslike_f: 31.1,
            windchill_c: -0.5,
            windchill_f: 31.1,
            heatindex_c: 3.4,
            heatindex_f: 38.1,
            dewpoint_c: -6.2,
            dewpoint_f: 20.8,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.1,
            gust_kph: 19.4
          },
          {
            time_epoch: 1606050000,
            time: "2020-11-22 22:00",
            temp_c: 3.7,
            temp_f: 38.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 309,
            wind_dir: "NW",
            pressure_mb: 1025.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 51,
            cloud: 6,
            feelslike_c: 0.0,
            feelslike_f: 32.0,
            windchill_c: 0.0,
            windchill_f: 32.0,
            heatindex_c: 3.7,
            heatindex_f: 38.7,
            dewpoint_c: -5.6,
            dewpoint_f: 21.9,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 11.4,
            gust_kph: 18.4
          },
          {
            time_epoch: 1606053600,
            time: "2020-11-22 23:00",
            temp_c: 3.9,
            temp_f: 39.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 307,
            wind_dir: "NW",
            pressure_mb: 1025.0,
            pressure_in: 30.8,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 3,
            feelslike_c: 0.5,
            feelslike_f: 32.9,
            windchill_c: 0.5,
            windchill_f: 32.9,
            heatindex_c: 3.9,
            heatindex_f: 39.0,
            dewpoint_c: -4.9,
            dewpoint_f: 23.2,
            will_it_rain: 0,
            chance_of_rain: "0",
            will_it_snow: 0,
            chance_of_snow: "0",
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9
          }
        ]
      }
    ]
  },
  alert: {}
};

export default dummy;
